version: '3'

tasks:
  default:
    desc: 利用可能なタスクを表示
    cmds:
      - task -l
    silent: true

  frontend:install:
    desc: フロントエンド依存関係をインストール
    dir: frontend
    cmds:
      - npm install

  frontend:dev:
    desc: フロントエンド開発サーバーを起動
    dir: frontend
    cmds:
      - npm run dev
    interactive: true

  frontend:build:
    desc: フロントエンドを本番ビルド
    dir: frontend
    cmds:
      - npm run build

  frontend:preview:
    desc: 本番ビルドをプレビュー
    dir: frontend
    cmds:
      - npm run preview

  frontend:lint:
    desc: ESLint を実行
    dir: frontend
    cmds:
      - npm run lint

  frontend:format:
    desc: Prettier でコード整形
    dir: frontend
    cmds:
      - npm run format

  frontend:format-check:
    desc: Prettier の整形チェック
    dir: frontend
    cmds:
      - npm run format:check

  frontend:typecheck:
    desc: TypeScript の型チェックを実行
    dir: frontend
    cmds:
      - npm run typecheck

  frontend:check:
    desc: lint・型チェック・整形チェックを実行
    dir: frontend
    cmds:
      - npm run lint
      - npm run typecheck
      - npm run format:check

  backend:install:
    desc: バックエンド依存関係をインストール（uv + pyproject）
    dir: backend
    cmds:
      - uv sync --no-install-project

  backend:dev:
    desc: バックエンド開発サーバーを起動
    dir: backend
    cmds:
      - uv run --no-project uvicorn main:app --reload --port 8000 --app-dir src
    interactive: true

  backend:lint:
    desc: Ruff でリントを実行
    dir: backend
    cmds:
      - uv run ruff check src

  backend:format:
    desc: Ruff でコード整形
    dir: backend
    cmds:
      - uv run ruff format src

  backend:format-check:
    desc: Ruff の整形チェック
    dir: backend
    cmds:
      - uv run ruff format --check src

  backend:typecheck:
    desc: ty で型チェックを実行
    dir: backend
    cmds:
      - uv run ty check src

  backend:check:
    desc: lint・型チェック・整形チェックを実行
    dir: backend
    cmds:
      - uv run ruff check src
      - uv run ty check src
      - uv run ruff format --check src
