version: '3'

tasks:
  default:
    desc: 利用可能なタスクを表示
    cmds:
      - task -l
    silent: true

  check:
    desc: バックエンド・フロントエンドのチェックを実行
    cmds:
      - task backend:check
      - task frontend:check

  frontend:install:
    desc: フロントエンド依存関係をインストール
    dir: frontend
    cmds:
      - npm install

  frontend:dev:
    desc: フロントエンド開発サーバーを起動
    dir: frontend
    cmds:
      - npm run dev
    interactive: true

  frontend:build:
    desc: フロントエンドを本番ビルド
    dir: frontend
    cmds:
      - npm run build

  frontend:preview:
    desc: 本番ビルドをプレビュー
    dir: frontend
    cmds:
      - npm run preview

  frontend:lint:
    desc: ESLint を実行
    dir: frontend
    cmds:
      - npm run lint

  frontend:format:
    desc: Prettier でコード整形
    dir: frontend
    cmds:
      - npm run format

  frontend:format-check:
    desc: Prettier の整形チェック
    dir: frontend
    cmds:
      - npm run format:check

  frontend:typecheck:
    desc: TypeScript の型チェックを実行
    dir: frontend
    cmds:
      - npm run typecheck

  frontend:check:
    desc: lint・型チェック・整形チェックを実行
    dir: frontend
    cmds:
      - npm run lint
      - npm run typecheck
      - npm run format:check

  backend:install:
    desc: バックエンド依存関係をインストール（uv + pyproject）
    dir: backend
    cmds:
      - uv sync --no-install-project

  backend:dev:
    desc: バックエンド開発サーバーを起動
    dir: backend
    cmds:
      - task env:decrypt
      - uv run --no-project uvicorn main:app --reload --port 8000 --app-dir src
    interactive: true

  backend:lint:
    desc: Ruff でリントを実行
    dir: backend
    cmds:
      - uv run ruff check src

  backend:format:
    desc: Ruff でコード整形
    dir: backend
    cmds:
      - uv run ruff format src

  backend:format-check:
    desc: Ruff の整形チェック
    dir: backend
    cmds:
      - uv run ruff format --check src

  backend:typecheck:
    desc: ty で型チェックを実行
    dir: backend
    cmds:
      - uv run ty check src

  backend:check:
    desc: lint・型チェック・整形チェックを実行
    dir: backend
    cmds:
      - uv run ruff check src
      - uv run ty check src
      - uv run ruff format --check src

  env:decrypt:
    desc: .env.enc を復号して backend/.env を生成
    cmds:
      - |
        bash -lc '
          key_file="${SOPS_AGE_KEY_FILE:-}"
          if [ -z "$key_file" ]; then
            if [ -f "$HOME/.config/sops/age/keys.txt" ]; then
              key_file="$HOME/.config/sops/age/keys.txt"
            elif [ -f "$HOME/.config/age/key.txt" ]; then
              key_file="$HOME/.config/age/key.txt"
            fi
          fi

          if [ -f backend/.env.enc ]; then
            command -v sops >/dev/null 2>&1 || {
              echo "sops が見つかりません（backend/.env.enc の復号に必要です）"
              echo "macOS の場合: brew install sops"
              if [ -s backend/.env ]; then
                echo "既存の backend/.env を利用します"
                exit 0
              fi
              exit 1
            }

            tmp_file="$(mktemp backend/.env.tmp.XXXXXX)"
            if [ -n "$key_file" ]; then
              export SOPS_AGE_KEY_FILE="$key_file"
            fi

            if sops -d --input-type dotenv --output-type dotenv backend/.env.enc > "$tmp_file"; then
              mv "$tmp_file" backend/.env
              echo "backend/.env.enc を復号して backend/.env を生成しました"
            else
              rm -f "$tmp_file"
              if [ -s backend/.env ]; then
                echo "backend/.env.enc の復号に失敗したため、既存の backend/.env を利用します"
              else
                echo "backend/.env.enc の復号に失敗し、利用可能な backend/.env もありません"
                echo "SOPS_AGE_KEY_FILE を設定するか、~/.config/sops/age/keys.txt または ~/.config/age/key.txt に age 秘密鍵を配置してください"
                exit 1
              fi
            fi
          elif [ -s backend/.env ]; then
            echo "backend/.env.enc がないため、既存の backend/.env を利用します"
          else
            echo "backend/.env.enc と backend/.env のどちらもありません"
            echo "backend/.env.example をコピーして backend/.env を作成するか、task env:encrypt で backend/.env.enc を作成してください"
            exit 1
          fi
        '

  env:encrypt:
    desc: backend/.env を暗号化して .env.enc を生成
    cmds:
      - bash -lc 'command -v sops >/dev/null 2>&1 || { echo "sops が見つかりません"; exit 1; }'
      - bash -lc 'test -f backend/.env || { echo "backend/.env がありません"; exit 1; }'
      - bash -lc 'sops -e --input-type dotenv --output-type dotenv --output backend/.env.enc backend/.env'
